# Generated by Django 5.1.4 on 2024-12-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default=1234, max_length=120),
            preserve_default=False,
        ),
    ]
