# Generated by Django 5.1.4 on 2024-12-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_rename_password_profile_password1_profile_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password2',
            new_name='password',
        ),
    ]
